.TH example 1 "July 13, 2025" "1.0" "Example Manual"
.SH NAME
example \- a simple man page written in Roff
.SH SYNOPSIS
.B example
[\fIOPTIONS\fR]
.SH DESCRIPTION
This is a simple example of a Unix manual page written in the Roff (troff) language.

It shows how to use basic macros like .TH, .SH, .B, and .I.

.SH OPTIONS
.TP
.B \-h
Show help information.

.TP
.B \-v
Show version number.

.SH AUTHOR
Written by DMS-Menula.

.SH SEE ALSO
.BR man (1),
.BR groff (1),
.BR nroff (1)
